### ISSUE TITLE
Do pre-release test with "dumb" inputs

### ISSUE THREAD

**Issue by liammulh** [numberscope/frontscope#113]
Before we go live / release frontscope, we should do a manual test where we supply weird/dumb inputs to the params. For example, we could provide way too many numbers (1111111111111111111111111111111111111111111), etc.

Related to https://github.com/numberscope/frontscope/pull/108.

**Comment by katestange** [comment]
As an example, if you choose such a gigantic bigint for "Mod dimension" in the Mod Fill visualizer, then the website will hang.

**Comment by gwhitney** [comment]
Labeling this as a documentation and maintenance issue, since I think the only way to implement a manual test is by documenting that it should be done (on some/all PRs, or just before any installation into production, etc.)

**Comment by gwhitney** [comment]
Actually, we should have some tests like this in #420, which should resolve this issue.

**Comment by gwhitney** [comment]
This is a great issue to have come up now. Turns out that it is not really possible to gracefully handle the "gigantic mod dimension" issue until the sketch is available, at which point it is no longer possible to add errors or warnings to the parameters tab. So  to properly deal with the one specific concern described here, it will be necessary to fully address #112 and make the sequence, visualization, and their individual parameter statuses accessible/changeable throughout the lifetime of a specimen (and not just at checkParameters time).

Oh and @katestange & @vectornaut we could really use some more really dumb ideas for crazy interactions/inputes that someone might do. Thanks.

**Comment by katestange** [comment]
I'll get my seven year old on it pronto.  He loves that task.

**Comment by gwhitney** [comment]
Implementation "complete" (we can always use more dumbness!) in ui2 per #473. Closing.
