### ISSUE TITLE
add getFactors() to sequences

### ISSUE THREAD

**Issue by katestange** [numberscope/frontscope#116]
Now the backend can provide factorizations.  We need visualizers to have access to this information through the sequences class, with something like `.getFactors()`.

**Comment by gwhitney** [comment]
In meeting, we discussed that the argument to getFactors should be the same as to getElement, and it should return a list of pairs of integers (factor, power).

**Comment by liam-mulhall** [comment]
Part of @katestange's work on https://github.com/numberscope/frontscope/issues/115.

**Comment by liam-mulhall** [comment]
This blocks progress on https://github.com/numberscope/frontscope/issues/115.

**Comment by gwhitney** [comment]
If we put .getFactors() in the generic interface, as it seems we need to for the sort of application that Kate has in mind, then we are then going to also have to implement .getFactors() for sequences that currently don't hit the backend at all. So we will encounter the question of how we should factor a specific number in frontscope: ask the backend for an individual factorization? Find a math package for JavaScript that does factorization? (Sadly mathjs does not yet have any factoring capability.) Adopt a hybrid approach: factor numbers less than some cutoff in JavaScript, and ask the backend about big ones where it's worth the http roundtrip?

**Comment by katestange** [comment]
Oh, very good point!  Are we planning to cache formula-generated sequences in the backend also, in the long run?  For now, as you say, we do not.  I've spent a decent amount of time looking for good javascript factorization packages and from what I recall it wasn't a great selection.  I think in the long run / ideal world we should add factorization to math.js.  But in the mid term, the hybrid approach seems good maybe?  For getting a first version of this issue into a PR, though, would it be reasonable to do some super basic factoring in javascript (maybe even just trial division), so that the functionality exists, although slow and/or limited (it could refuse to factor anything too big; even the backend does that, albeit with a nice high bound)?

**Comment by gwhitney** [comment]
> planning to cache formula-generated sequences in the backend also, in the long run?

Indeed, that's why I've been spending so much time beefing up math.js. The idea is to parse the formula and canonicalize it on the front end, pass the parse tree to the back end as JSON, and in the back end compute and store the values for that formula, taking advantage of any already-stored subformulas. (My current thinking is not to store every subformula, but to use the fact that a specific formula was requested as the signal that that particular formula is worth storing, and hence factoring as well.)

I'll be honest, in this vision, ultimately there is only need for one Sequence class -- the formula one that allows OEIS names as symbols. Then if you want A000045 unchanged, you just type that; or you could double every other term of it with `2*A000045(2*n)`, or if you want just the triangular numbers you type `(n+1)n/2`, and if you want all natural numbers starting at three you type `n;n>2` (or `k;k>2` if you like since the quantifier on the right makes the index variable explicit). If you want random numbers, we'd have some sort of rand() function for you. (And obviously we have to avoid any caching for sequences that have a rand() anywhere within them... so there will always need to be factorization of some sort in the front end.)

In this scenario, there wouldn't be any need for multiple different user-visible varieties of Sequences. That would in turn mean that we could replace the sequence menu with just a text entry box for the Sequence formula, making it easy to have more than one such box for Visualizers that can/want to deal with more than one Sequence.  But I am not wedded to that particular direction for Sequence input if others don't find it as compelling.

**Comment by gwhitney** [comment]
Right well in the world where we take new visitors to one of several pre-cooked nice displays, there would already be something in the Sequence entry box...

**Comment by liam-mulhall** [comment]
Add a `getFactors` in the interface with a default response "there are no factorizations". Override this with OEIS sequence factorizations from the backend. The future OEIS formula will also have to support this.
