### ISSUE TITLE
zeroes don't show up in parameter pop-ups

### ISSUE THREAD

**Issue by katestange** [numberscope/frontscope#57]
When the default to a param (for a sequence or a visualizer) is 0, it shows an empty box in the pop-up parameters fields for the user.  This still seems to evaluate to 0 if you move forward without putting something in the box.

**Comment by gwhitney** [comment]
I saw this in merging #53, and added a workaround by changing the default from the integer `0` to the one-character string `'0'`. Kate, you can decide if you're comfortable with that workaround, in which case close this issue, or if you would like to resolve the underlying situation so that a default of the integer `0` would show up in a parameter pop-up, in which case just confirm that with another comment here and leave the issue open.

**Comment by katestange** [comment]
If you don't see any future problem with this workaround, I don't have any problem with it.  My understanding is that what's in the box is received as a string when it is sent back into the program anyway (correct?), so I don't see a problem.  The only other question I can think of:  is there going to be another variation on this problem with any other inputs?  Or is integer `0` really the only case this will happen?

**Comment by gwhitney** [comment]
It's Javascript false-y values. Those are null and undefined (which we wouldn't want to show up anyway), false (which is irrelevant because booleans use checkboxes not text entries), the empty string (which is empty anyway), and the Number 0, which we can work around with `'0'`. So yes, that is really the only case of concern. So closing with a wontfix because of the relatively straightforward workaround.
