### ISSUE TITLE
new param types for sequences and visualizers

### ISSUE THREAD

**Issue by katestange** [numberscope/frontscope#62]
Right now, `src/shared/ParamType.ts` lists only three types of possible parameters for visualizers and sequences: number, text and boolean.  In #59, I find that I would like to have a "multiple choice" type that will allow me to choose from 4 different colouring schemes.  As a workaround, I used an integer that I interpret as such a choice.  It would be nice to have a general "multiple choice" functionality.  (And then use it in the Chaos Visualizer #59.)

**Comment by katestange** [comment]
It would also be good to have a colour-picker parameter type, eventually.  Maybe even a palette picker.  Could be part of this issue or a separate one once we work out details of what would be needed.

**Comment by gwhitney** [comment]
> It would also be good to have a colour-picker parameter type, eventually. Maybe even a palette picker. Could be part of this issue or a separate one once we work out details of what would be needed.

I think that has to be a separate issue, for two reasons: (A) focused issues are more easily actionable than portmanteau ones, and (B) I think the palette question is really intertwined with the UI design. For example, we might just want to have a dedicated palette panel or pulldown or menu or something like that, creating a global palette that all visualizers would use so that they would all always be in harmony, or it might be that each Bundle has an associated palette so that you could have two very different color schemes side by side -- this will definitely take some thought. We want to make the interface feel as effortless as possible while providing as much of the power that visitors will actually want as we can. So partly this will need either a guess or some information gathering about whether folks would want to have, say, a light background visualizer next to a dark one, etc.

**Comment by gwhitney** [comment]
Working on a PR that will add enum, BigInt, and array types to those handled by the param panel, as well as add a color picker. In addition, once the values have been validated, they will automatically end up in top-level properly-typed properties of the sequence or visualizer. So this should hopefully enhance writing sequences/visualizers.
