### ISSUE TITLE
Add GitHub Issue Templates.

### ISSUE THREAD

**Issue by liammulh** [numberscope/frontscope#66]
It would be nice to have (at least) a standard bug report template that everyone uses so that it's easier to understand, reproduce, and generally document bugs. I think it's also important to include platform details in bug reports. In the future, it might make sense to add a feature request template.

GitHub lets you create templates for issues: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository.

I'd recommend having a section for a description of the bug, a section for steps to reproduce the bug, and a section for platform details (OS/browser).

**Comment by katestange** [comment]
I think this sounds like an excellent idea.

**Comment by gwhitney** [comment]
I am totally fine with this. The configuration files are in .github/ISSUE_TEMPLATES within the file tree of the repository contents, and so can be created by an ordinary PR. The only recommendation I'd add is that if we add a bug report template we also add a feature request template (which would auto-label as "enhancement") and also allow blank issues for things that don't neatly fall into either category. Since there seems to be consensus, I'm going to relabel this issue.

**Comment by liam-mulhall** [comment]
@katestange, I don't have permission to access the settings of the repository, so I can't do this. Labeling this issue as blocked.

**Comment by katestange** [comment]
Try now, I tried to upgrade your access.

**Comment by liam-mulhall** [comment]
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository is telling me to look in the "Features" section of the repo, but I don't see a "Set up templates" button there (or an Issues section for that matter):
![Screenshot from 2022-06-07 17-42-28](https://user-images.githubusercontent.com/60749003/172501554-c43ac941-e4af-4d36-9f3b-2b3c4735e6a2.png)

**Comment by katestange** [comment]
I tried again.

**Comment by liam-mulhall** [comment]
Okay, I see the issue template button now!

**Comment by gwhitney** [comment]
We have a template in place, so closing.
