### ISSUE TITLE
"hot-modifying" the parameters of a visualizer

### ISSUE THREAD

**Issue by katestange** [numberscope/frontscope#68]
Have the parameters of the visualizer accessible (side panel?) during the main "draw" view.  If parameters are changed, immediately interrupt and redraw (no submit button).

**Comment by khaledallen** [comment]
[Also an item on the todo.md]

**Comment by katestange** [comment]
I'm adding the "important" tag to this because I think this is the main obstruction to "having fun" with numberscope at the moment (besides adding more visualizers).

**Comment by gwhitney** [comment]
In light of #108, there was more discussion of this issue today. In particular, the question came up of whether a visualizer in progress should "just keep drawing" with the new parameters or clear itself and start again from the beginning with the new parameters. The consensus was that ideally it should be up to the visualizer -- when it is "notified" of a change, it should be able to analyze what's changed and decide which action to take. If it keeps on going but the user wanted to restart, there should also be a way to do that. It is not currently clear what the protocol should be for the UI notifying the visualizer of a change, though. So that piece of this issue could use a solid proposal.

**Comment by gwhitney** [comment]
Also in the discussion today, @liam-mulhall mentioned that there were Vue libraries for state management that might be relevant to this issue. (Any links you might have, Liam, would be welcome.)

**Comment by liam-mulhall** [comment]
Pinia for state management: https://pinia.vuejs.org/.

**Comment by liam-mulhall** [comment]
For discussion at weekly meeting: Do we want this before we run Numberscope in Fall 2022?

**Comment by liam-mulhall** [comment]
It would be nice to have this for the Fall 2022 undergrads. KS: "Ideally, but not necessarily."

**Comment by liammulh** [comment]
We discussed this in today's (10/31) dev meeting.

- KS: We need some way of re-running `setup()`.
- GW: We can't tell p5 to call `setup()` again?

- KS & GW: We need to distinguish between restart and hot modify.
    - restart is new instance, i.e. new `setup()`
    - hot modify is modify `draw()`
- KS & GW: Programmer should know there are two ways to change, they need to be careful about this.

- GW: What if sequence changes?
  - Do we completely re-draw?
  - Or do we continue with new sequence?
- KS: Why not both functionalities? (Allow user to decide.)
    - If you want it to hot-modify, then do that.
    - If you want it to re-setup, then do that.

**Comment by liammulh** [comment]
We also talked about the UI for params today (10/31).

- GW: The first step would be to use a side panel (or something similar) instead of a modal.
  - Then we could work on making sure the communication between the side panel and the visualization is live.

**Comment by gwhitney** [comment]
Implemented in ui2. :) closing.
