### ISSUE TITLE
Add docs for creating unit tests with Vitest

### ISSUE THREAD

**Issue by liammulh** [numberscope/frontscope#73]
As part of https://github.com/numberscope/frontscope/pull/72, @gwhitney suggested I make an issue about adding docs for tests.

As of this writing, the plan is to add generic testing functionality of Jest on top of Vue Test Utils. Once we have both Vue Test Utils and generic Jest working, I'll start on this issue.

EDIT: The original comments in this issue are sort of stale. See https://github.com/numberscope/frontscope/issues/73#issuecomment-1379478361.

The issue that tracks this issue is https://github.com/numberscope/frontscope/issues/25.

**Comment by gwhitney** [comment]
Indeed. I think what I was getting at with suggesting this issue is that we also need some guide as to how to create a test for a new module (although the existing tests go a long way in showing how to do that, I suspect some narrative would be helpful as well) as well as guidelines on what aspects of a module should be tested and any other conventions we have for our tests.

**Comment by liammulh** [comment]
I'm not working on this right now. Unassigning myself.

**Comment by gwhitney** [comment]
This should be folded into #420. Setting milestone accordingly.

**Comment by gwhitney** [comment]
Completed in ui2 per #420. Closing.
