### ISSUE TITLE
What is the "The Scope" button for?

### ISSUE THREAD

**Issue by liam-mulhall** [numberscope/frontscope#79]
I think this button is a bit vague. Is it supposed to lead to the `/canvas` page?

**Comment by katestange** [comment]
Yes: it means "go play with the numberscope."  I'm not wedded to the naming on the buttons, but that was the original intention.  In particular, in the end UI experience, we may want to just be at the scope when arriving at the page, instead of having to click anything at all.

**Comment by gwhitney** [comment]
The current "landing page" is pretty attractive, so I think we should keep it at least until the default Numberscope initializes to something equally eye-catching, and then only if the Numberscope is pretty self-explanatory as to what it's for.  Since you might have navigated to the user manual (or when it exists, to the specimens page), I think it will be reasonable to leave a button in the nav bar for the Numberscope itself even if we eventually change the base url to go directly to the Numberscope. The only oddity is that both the logo and the "The Scope" button go to the Numberscope. While there are distinct landing and scope tool pages, it seems to me that the logo should go to the landing page and "The Scope" should go to the Numberscope tool. So I will file an issue to that effect; and if at some point we make the Numberscope tool be the home page, we can decide what to do about the nav bar then.

@liam-mulhall, I think these comments and the filing of the new issue have resolved this issue. If you agree, please close it.

**Comment by liam-mulhall** [comment]
> it seems to me that the logo should go to the landing page and "The Scope" should go to the Numberscope tool

This is the behavior I would expect.

I
